using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace Yape.Entities
{
    /// <summary>
    /// Represents the Person entity, which stores personal identification and contact information.
    /// This class is mapped to the "Person" table in the database.
    /// </summary>
    [Table("Person")]
    public class Person
    {
        /// <summary>
        /// Gets or sets the unique identifier for the person.
        /// This value is auto-generated by the database.
        /// </summary>
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long Id { get; set; }

        /// <summary>
        /// Gets or sets the person's cell phone number.
        /// </summary>
        public long CellPhoneNumber { get; set; }

        /// <summary>
        /// Gets or sets the first name of the person.
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the last name of the person.
        /// </summary>
        public string LastName { get; set; }

        /// <summary>
        /// Gets or sets the type of identification document (e.g., ID, Passport).
        /// </summary>
        public string DocumentType { get; set; }

        /// <summary>
        /// Gets or sets the unique document number associated with the person.
        /// </summary>
        public string DocumentNumber { get; set; }
    }
}
